import React from 'react';
import { BrainCircuit, Glasses, Globe2, BarChart3, Clock, ShieldCheck } from 'lucide-react';

const Features: React.FC = () => {
  const features = [
    {
      icon: <BrainCircuit size={32} className="text-brand-accent" />,
      title: "Adaptive Neural Pathways",
      description: "Our curriculum isn't static. It evolves in real-time based on your learning velocity and retention rates."
    },
    {
      icon: <Glasses size={32} className="text-purple-400" />,
      title: "VR Immersion Labs",
      description: "Practice ordering coffee in a virtual Paris or negotiating a deal in a digital Tokyo from our Singapore campus."
    },
    {
      icon: <BarChart3 size={32} className="text-green-400" />,
      title: "Predictive Analytics",
      description: "Visual dashboards track your fluency probability. Know exactly when you'll be exam-ready."
    },
    {
      icon: <Globe2 size={32} className="text-blue-400" />,
      title: "Global Mesh Network",
      description: "Connect instantly with native speakers and fellow students across the global inlingua network."
    },
    {
      icon: <Clock size={32} className="text-orange-400" />,
      title: "Just-in-Time Learning",
      description: "Micro-lessons generated by AI specifically for the meeting or trip you have tomorrow."
    },
    {
      icon: <ShieldCheck size={32} className="text-red-400" />,
      title: "Certified Excellence",
      description: "While our tech is from 2030, our certification is grounded in 50 years of educational trust."
    }
  ];

  return (
    <section id="methodology" className="py-24 relative bg-slate-900/30">
      <div className="max-w-7xl mx-auto px-4 md:px-8">
        <div className="text-center mb-16">
          <h2 className="text-sm font-mono text-brand-primary tracking-widest uppercase mb-4">The Upgrade</h2>
          <h3 className="text-3xl md:text-5xl font-display font-bold text-white mb-6">Built for the Speed of Thought</h3>
          <p className="text-slate-400 max-w-2xl mx-auto">
            Traditional language schools are analog. We are digital-native. Experience the difference of a fully integrated learning ecosystem.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <div key={index} className="glass-panel p-8 rounded-2xl hover:bg-white/10 transition-all group border border-transparent hover:border-brand-primary/30">
              <div className="mb-6 p-4 rounded-xl bg-slate-900 inline-block border border-white/5 group-hover:scale-110 transition-transform duration-300">
                {feature.icon}
              </div>
              <h4 className="text-xl font-bold text-white mb-3 font-display">{feature.title}</h4>
              <p className="text-slate-400 leading-relaxed text-sm">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;